<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest><AssemblyName>LogLens</AssemblyName><Product>LogLens</Product>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../LogLens.Core/LogLens.Core.csproj" /><ProjectReference Include="../LogLens.Windows/LogLens.Windows.csproj" /></ItemGroup>
</Project>
